package com.loanapproval.dss.policy;

import java.math.BigDecimal;

public record CreditPolicyDefinition(
        String version,
        BigDecimal unsecuredAnnualRate,
        BigDecimal securedAnnualRate,
        BigDecimal unsecuredIncomeMultiple,
        BigDecimal securedVehicleLtv,
        BigDecimal maxDsr,
        BigDecimal unsecuredProductCap,
        BigDecimal securedProductCap,
        BigDecimal riskAdjustmentA,
        BigDecimal riskAdjustmentB,
        BigDecimal riskAdjustmentC,
        BigDecimal riskAdjustmentD,
        double dssWeightDti,
        double dssWeightIncome,
        double dssWeightCreditHistory,
        double dssWeightBurden,
        double dssWeightEmployment,
        double dssWeightAge,
        double dssWeightCollateral,
        double dssWeightPurpose,
        double dssWeightVerification,
        int dssScoreMin,
        int dssScoreMax,
        double dssScoreMultiplier,
        int dssRankAThreshold,
        int dssRankBThreshold,
        int dssRankCThreshold,
        double dtiLowThreshold,
        double dtiHighDowngradeThreshold,
        double dtiModerateDowngradeThreshold,
        double dtiExtremeThreshold,
        double dtiRejectThreshold) {

    public static CreditPolicyDefinition defaultPolicy() {
        return new CreditPolicyDefinition(
                "VND_RETAIL_LOAN_POLICY_2026_05",
                BigDecimal.valueOf(0.12),
                BigDecimal.valueOf(0.105),
                BigDecimal.valueOf(10),
                BigDecimal.valueOf(0.70),
                BigDecimal.valueOf(0.50),
                BigDecimal.valueOf(300_000_000L),
                BigDecimal.valueOf(1_500_000_000L),
                BigDecimal.ONE,
                BigDecimal.valueOf(0.85),
                BigDecimal.valueOf(0.65),
                BigDecimal.ZERO,
                0.23,
                0.18,
                0.15,
                0.12,
                0.12,
                0.07,
                0.07,
                0.04,
                0.02,
                300,
                850,
                5.5,
                780,
                700,
                620,
                35.0,
                55.0,
                45.0,
                75.0,
                60.0);
    }
}
