ALTER TABLE secured_loan_procedures
    ADD COLUMN contract_number VARCHAR(100) NULL AFTER staff_user_id,
    ADD COLUMN contract_signed_date DATE NULL AFTER contract_number,
    ADD COLUMN nationality VARCHAR(80) NULL AFTER contract_signed_date,
    ADD COLUMN identity_document_number VARCHAR(100) NULL AFTER nationality,
    ADD COLUMN permanent_address VARCHAR(255) NULL AFTER identity_document_number,
    ADD COLUMN current_address VARCHAR(255) NULL AFTER permanent_address,
    ADD COLUMN occupation VARCHAR(120) NULL AFTER current_address,
    ADD COLUMN job_title VARCHAR(120) NULL AFTER occupation,
    ADD COLUMN asset_type VARCHAR(100) NULL AFTER job_title,
    ADD COLUMN asset_manufacturer VARCHAR(120) NULL AFTER asset_type,
    ADD COLUMN engine_number VARCHAR(100) NULL AFTER asset_manufacturer,
    ADD COLUMN frame_number VARCHAR(100) NULL AFTER engine_number,
    ADD COLUMN sale_price DECIMAL(15,2) NULL AFTER frame_number,
    ADD COLUMN down_payment DECIMAL(15,2) NULL AFTER sale_price,
    ADD COLUMN monthly_interest_rate DECIMAL(10,6) NULL AFTER down_payment,
    ADD COLUMN monthly_payment_amount DECIMAL(15,2) NULL AFTER monthly_interest_rate,
    ADD COLUMN first_payment_date DATE NULL AFTER monthly_payment_amount,
    ADD COLUMN monthly_payment_day VARCHAR(30) NULL AFTER first_payment_date,
    ADD COLUMN final_payment_date DATE NULL AFTER monthly_payment_day,
    ADD COLUMN original_certificate_received BOOLEAN NOT NULL DEFAULT FALSE AFTER final_payment_date,
    ADD COLUMN certified_copy_delivered BOOLEAN NOT NULL DEFAULT FALSE AFTER original_certificate_received,
    ADD COLUMN collateral_registration_completed BOOLEAN NOT NULL DEFAULT FALSE AFTER certified_copy_delivered,
    ADD COLUMN dispute_checked BOOLEAN NOT NULL DEFAULT FALSE AFTER collateral_registration_completed,
    ADD COLUMN seizure_notice_acknowledged BOOLEAN NOT NULL DEFAULT FALSE AFTER dispute_checked;
