package com.loanapproval.dss.notification;

public enum NotificationCategory {
    INFORMATION_REVIEW_SUBMITTED,
    INFORMATION_REVIEW_COMPLETED,
    LOAN_APPLICATION_SUBMITTED,
    LOAN_DECISION_UPDATED,
    LOAN_DISBURSED,
    APPOINTMENT_SCHEDULED,
    APPOINTMENT_NO_SHOW,
    CONTRACT_CREATED,
    LOAN_CONTRACT_ACCEPTED,
    LOAN_WITHDRAWN,
    PAYMENT_CONFIRMATION_SUBMITTED,
    PAYMENT_CONFIRMED,
    PAYMENT_REJECTED,
    PAYMENT_DUE_SOON,
    LOAN_OVERDUE,
    LOAN_OVERDUE_RESOLVED,
    LOAN_CLOSED
}
