export const BLOCKING_APPLICATION_STATUSES = Object.freeze([
  "DRAFT",
  "PENDING",
  "NEEDS_MORE_INFO",
  "APPOINTMENT_SCHEDULED",
  "APPROVED",
  "CONTRACTED",
  "ACTIVE",
  "OVERDUE"
]);

export const CUSTOMER_WITHDRAWABLE_STATUSES = Object.freeze([
  "DRAFT",
  "PENDING",
  "NEEDS_MORE_INFO"
]);

export const MAX_ADDITIONAL_INFO_REQUESTS = 3;
export const DEFAULT_ADDITIONAL_INFO_DEADLINE_DAYS = 3;
