package com.loanapproval.dss.loan;

import java.math.BigDecimal;
import java.time.Instant;

public record LoanRecord(
        Long id,
        Long customerId,
        LoanType loanType,
        BigDecimal amount,
        Integer termMonths,
        LoanPurpose purpose,
        CollateralType collateralType,
        BigDecimal collateralValue,
        LoanStatus status,
        String finalReason,
        BigDecimal eligibleLimit,
        BigDecimal approvedAmount,
        Integer approvedTermMonths,
        BigDecimal approvedAnnualRate,
        BigDecimal approvedMonthlyPayment,
        String decisionPolicyVersion,
        String intakeNote,
        String additionalInfoRequestNote,
        Instant additionalInfoLastRequestedAt,
        Instant additionalInfoRequestDeadline,
        Integer additionalInfoRequestCount,
        Instant reviewDeadlineAt,
        Instant contractAcceptanceDeadlineAt,
        Instant createdAt,
        Instant updatedAt) {

    public LoanRecord(
            Long id,
            Long customerId,
            LoanType loanType,
            BigDecimal amount,
            Integer termMonths,
            LoanPurpose purpose,
            CollateralType collateralType,
            BigDecimal collateralValue,
            LoanStatus status,
            String finalReason,
            BigDecimal eligibleLimit,
            BigDecimal approvedAmount,
            Integer approvedTermMonths,
            BigDecimal approvedAnnualRate,
            BigDecimal approvedMonthlyPayment,
            String decisionPolicyVersion,
            String intakeNote,
            Instant createdAt,
            Instant updatedAt) {
        this(
                id,
                customerId,
                loanType,
                amount,
                termMonths,
                purpose,
                collateralType,
                collateralValue,
                status,
                finalReason,
                eligibleLimit,
                approvedAmount,
                approvedTermMonths,
                approvedAnnualRate,
                approvedMonthlyPayment,
                decisionPolicyVersion,
                intakeNote,
                null,
                null,
                null,
                0,
                null,
                null,
                createdAt,
                updatedAt);
    }

    public LoanRecord(
            Long id,
            Long customerId,
            LoanType loanType,
            BigDecimal amount,
            Integer termMonths,
            LoanPurpose purpose,
            CollateralType collateralType,
            BigDecimal collateralValue,
            LoanStatus status,
            String finalReason,
            BigDecimal eligibleLimit,
            BigDecimal approvedAmount,
            Integer approvedTermMonths,
            BigDecimal approvedAnnualRate,
            BigDecimal approvedMonthlyPayment,
            String decisionPolicyVersion,
            String intakeNote,
            String additionalInfoRequestNote,
            Instant additionalInfoLastRequestedAt,
            Instant additionalInfoRequestDeadline,
            Integer additionalInfoRequestCount,
            Instant createdAt,
            Instant updatedAt) {
        this(
                id,
                customerId,
                loanType,
                amount,
                termMonths,
                purpose,
                collateralType,
                collateralValue,
                status,
                finalReason,
                eligibleLimit,
                approvedAmount,
                approvedTermMonths,
                approvedAnnualRate,
                approvedMonthlyPayment,
                decisionPolicyVersion,
                intakeNote,
                additionalInfoRequestNote,
                additionalInfoLastRequestedAt,
                additionalInfoRequestDeadline,
                additionalInfoRequestCount,
                null,
                null,
                createdAt,
                updatedAt);
    }
}
